"""
Django settings for iot_app project.

Generated by 'django-admin startproject' using Django 6.0.3.

Environments supported:
  - LOCAL  : PostgreSQL local (default cuando LOCAL_DB=True en .env)
  - SUPABASE: PostgreSQL en Supabase (cuando LOCAL_DB=False en .env)

Variables de entorno requeridas → ver archivo .env.example
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# ─── Cargar variables del archivo .env ────────────────────────────────────────
# load_dotenv() busca el archivo .env en la raíz del proyecto (BASE_DIR)
# y carga sus pares KEY=VALUE como variables de entorno del proceso.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# ─── SEGURIDAD ─────────────────────────────────────────────────────────────────
# NUNCA dejar la SECRET_KEY hardcodeada en producción.
# Se lee desde la variable de entorno SECRET_KEY definida en .env
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-only-for-dev')

# DEBUG debe ser False en producción.
# En .env: DEBUG=True  o  DEBUG=False
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Hosts permitidos. En producción agregar el dominio real.
# Ejemplo en .env: ALLOWED_HOSTS=miapp.com,www.miapp.com
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []


# ─── APLICACIONES ──────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iot_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iot_app.wsgi.application'


# ─── BASE DE DATOS ─────────────────────────────────────────────────────────────
#
# Se selecciona automáticamente según la variable LOCAL_DB en .env:
#
#   LOCAL_DB=True   → PostgreSQL local (localhost)
#   LOCAL_DB=False  → Supabase (PostgreSQL remoto vía Transaction Pooler)
#
# ┌─────────────────────────────────────────────────────────────────────────┐
# │  Para instalar el driver:  pip install psycopg2-binary                  │
# │  (o psycopg2 para producción compilada)                                 │
# └─────────────────────────────────────────────────────────────────────────┘

USE_LOCAL_DB = os.environ.get('LOCAL_DB', 'True') == 'True'

if USE_LOCAL_DB:
    # ── PostgreSQL LOCAL ──────────────────────────────────────────────────────
    # Requiere tener PostgreSQL instalado y una base de datos creada.
    # Crear BD:  psql -U postgres -c "CREATE DATABASE iot_db;"
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql',
            'NAME':     os.environ.get('LOCAL_DB_NAME',     'iot_db'),
            'USER':     os.environ.get('LOCAL_DB_USER',     'postgres'),
            'PASSWORD': os.environ.get('LOCAL_DB_PASSWORD', ''),
            'HOST':     os.environ.get('LOCAL_DB_HOST',     'localhost'),
            'PORT':     os.environ.get('LOCAL_DB_PORT',     '5432'),
            'OPTIONS': {
                # Tiempo máximo de espera para obtener una conexión del pool
                'connect_timeout': 10,
            },
        }
    }
else:
    # ── SUPABASE (PostgreSQL remoto) ──────────────────────────────────────────
    #
    # Supabase expone dos modos de conexión:
    #
    #   1. DIRECT (puerto 5432):
    #      - Conexión directa a Postgres, ideal para migraciones y scripts.
    #      - NO usar en producción con muchos requests (agota conexiones).
    #
    #   2. TRANSACTION POOLER (puerto 6543):  ← Recomendado para Django
    #      - PgBouncer gestiona el pool de conexiones.
    #      - Soporta muchos requests concurrentes.
    #      - Limitación: no soporta prepared statements →
    #        por eso se añade "disable_server_side_cursors": True
    #
    # Dónde encontrar los datos en Supabase:
    #   Project Settings → Database → Connection string → Python
    #
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql',
            # Nombre de la BD en Supabase (siempre "postgres" por defecto)
            'NAME':     os.environ.get('SUPABASE_DB_NAME',     'postgres'),
            # Usuario con formato: postgres.[project-ref]
            'USER':     os.environ.get('SUPABASE_DB_USER',     ''),
            # Contraseña de la BD (la que definiste al crear el proyecto)
            'PASSWORD': os.environ.get('SUPABASE_DB_PASSWORD', ''),
            # Host del Transaction Pooler:  aws-0-[region].pooler.supabase.com
            'HOST':     os.environ.get('SUPABASE_DB_HOST',     ''),
            # Puerto 6543 = Transaction Pooler  |  5432 = Direct connection
            'PORT':     os.environ.get('SUPABASE_DB_PORT',     '6543'),
            'OPTIONS': {
                # Requerido cuando se usa el Transaction Pooler (PgBouncer)
                # Evita prepared statements que no soporta PgBouncer en modo transaction
                'disable_server_side_cursors': True,
                # SSL requerido por Supabase
                'sslmode': 'require',
                'connect_timeout': 10,
            },
        }
    }


# ─── VALIDACIÓN DE CONTRASEÑAS ────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ─── INTERNACIONALIZACIÓN ─────────────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True


# ─── ARCHIVOS ESTÁTICOS ───────────────────────────────────────────────────────
STATIC_URL = 'static/'


# ─── CLAVE PRIMARIA POR DEFECTO ───────────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'